import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "Control"

[window]
decorations = "full"
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 10
y = 10
